name: beans_detection
description: Aplikasi Flutter UI Deteksi Kualitas Biji Kopi.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFF8EC"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/icon/app_icon.png
    - assets/images/logo/
    - assets/images/splash/
    - assets/images/placeholders/
    - assets/icons/
